# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-01 04:27
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('candicitizen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='won_first',
        ),
        migrations.RemoveField(
            model_name='group',
            name='won_second',
        ),
        migrations.AddField(
            model_name='group',
            name='nominees',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='winner',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
    ]
